#!/bin/sh

infile=$1
outfile="$HOME/linuxcnc/nc_files/`basename $1 .ngc`_laser.ngc"
echo Outputting to $outfile


cat >"$outfile" <<EOF
G94
F1400
G97
S100
G40
G21
EOF


#sed '	s/[(].*[)]//g;
sed '	s/G0.* Z5.*/M63 P0/gi;
	s/G0.* Z\[5.*/M63 P0/gi;
	s/G01 Z-.*/M62 P0/gi;
	s/G01 Z\[-.*/M62 P0/gi;
	s/G20//;
	s/Z\[[^]]*\]//g;
	s/Z[^ ]*//g;
	s/\%//;
	s/G00 X0.0000 Y0.0000//;
	s/^[	 ]*//;' "$infile" | \
grep -v '^$' >>"$outfile"


cat >>"$outfile" <<EOF
M65 P0
G01
EOF
